"""Add total_records field to ohlcv_data_collection

Revision ID: 4bb72ead09d8
Revises: f31ddc3f83bf
Create Date: 2025-01-15 02:35:16.753918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb72ead09d8'
down_revision = 'f31ddc3f83bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ohlcv_data_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_records', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ohlcv_data_collection', schema=None) as batch_op:
        batch_op.drop_column('total_records')

    # ### end Alembic commands ###
