"""Add status field and make fields nullable

Revision ID: 5d6c5941f4cf
Revises: 6e733aa6d9e6
Create Date: 2025-01-17 02:45:10.574014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6c5941f4cf'
down_revision = '6e733aa6d9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.alter_column('model_type',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('model_config',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('training_dataset_config',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('features_config',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('physical_location',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('accuracy_percent',
               existing_type=sa.FLOAT(precision=53),
               nullable=True)
        batch_op.alter_column('label_config',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_config', schema=None) as batch_op:
        batch_op.alter_column('label_config',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('accuracy_percent',
               existing_type=sa.FLOAT(precision=53),
               nullable=False)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('physical_location',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('features_config',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('training_dataset_config',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('model_config',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('model_type',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
