"""Add model_config table

Revision ID: 6e733aa6d9e6
Revises: 4bb72ead09d8
Create Date: 2025-01-17 00:10:48.880332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e733aa6d9e6'
down_revision = '4bb72ead09d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=255), nullable=False),
    sa.Column('model_config', sa.JSON(), nullable=False),
    sa.Column('coin_symbol', sa.String(length=50), nullable=False),
    sa.Column('training_dataset_name', sa.String(length=255), nullable=False),
    sa.Column('training_dataset_config', sa.JSON(), nullable=False),
    sa.Column('features_config', sa.JSON(), nullable=False),
    sa.Column('physical_location', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('accuracy_percent', sa.Float(), nullable=False),
    sa.Column('date_of_creation', sa.DateTime(), nullable=True),
    sa.Column('label_config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_config')
    # ### end Alembic commands ###
