"""Remove model_type column from model_config

Revision ID: f0950cbf934c
Revises: 5d6c5941f4cf
Create Date: 2025-01-18 17:04:31.160836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0950cbf934c'
down_revision = '5d6c5941f4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_config', schema=None) as batch_op:
        batch_op.drop_column('model_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_type', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
