"""Add ohlcv_data_collection table

Revision ID: f31ddc3f83bf
Revises: 9f87fbbfa955
Create Date: 2025-01-15 02:30:25.117918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31ddc3f83bf'
down_revision = '9f87fbbfa955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv_data_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_dataset', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('startdate', sa.BigInteger(), nullable=False),
    sa.Column('enddate', sa.BigInteger(), nullable=False),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ohlcv_data_collection')
    # ### end Alembic commands ###
